"""Add default to phone_number

Revision ID: 5d8b0f64bed0
Revises: f0952a777a36
Create Date: 2024-12-26 00:47:20.607871

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d8b0f64bed0"
down_revision: Union[str, None] = "f0952a777a36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "phone_number", existing_type=sa.VARCHAR(length=20), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "phone_number", existing_type=sa.VARCHAR(length=20), nullable=False)
    # ### end Alembic commands ###
