"""Add nickname

Revision ID: a64eb9edbfce
Revises: 5d8b0f64bed0
Create Date: 2024-12-26 13:22:51.562041

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a64eb9edbfce"
down_revision: Union[str, None] = "5d8b0f64bed0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("nickname", sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "nickname")
    # ### end Alembic commands ###
