"""Add place

Revision ID: eb7c15a34784
Revises: 29690dffa788
Create Date: 2024-12-30 17:47:04.939262

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eb7c15a34784"
down_revision: Union[str, None] = "29690dffa788"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "place",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "theme", sa.Enum("해변", "자연", "카페", "전시", "액티비티", "식당", name="themeenum"), nullable=False
        ),
        sa.Column(
            "address",
            sa.Enum(
                "제주시",
                "서귀포시",
                "한경면",
                "한림읍",
                "애월읍",
                "조천읍",
                "구좌읍",
                "대정읍",
                "안덕면",
                "남원읍",
                "표선면",
                "성산읍",
                name="regionenum",
            ),
            nullable=False,
        ),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("place")
    # ### end Alembic commands ###
