"""aa

Revision ID: 5553e6796784
Revises: 534ef42ff56a
Create Date: 2025-01-07 15:54:16.152248

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic.ddl import postgresql

# revision identifiers, used by Alembic.
revision: str = "5553e6796784"
down_revision: Union[str, None] = "534ef42ff56a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    imagesourcetype = sa.Enum("UPLOAD", "LINK", name="imagesourcetype")
    imagesourcetype.create(op.get_bind(), checkfirst=True)  # type: ignore
    op.add_column(
        "review_images", sa.Column("source_type", sa.Enum("UPLOAD", "LINK", name="imagesourcetype"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("review_images", "source_type")
    # ### end Alembic commands ###
