"""review_add_is_temporary

Revision ID: 3ea3ba4c1f26
Revises: a6bef0c0fb3d
Create Date: 2025-01-13 19:07:51.660817

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ea3ba4c1f26"
down_revision: Union[str, None] = "a6bef0c0fb3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("review_images", sa.Column("is_temporary", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("review_images", "is_temporary")
    # ### end Alembic commands ###
