"""Add Review, like, comment

Revision ID: 47eebca18c8d
Revises: d9619168fb67
Create Date: 2025-01-02 09:39:12.833580

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "47eebca18c8d"
down_revision: Union[str, None] = "e210e47788c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("like_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("review_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "likes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("review_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "review_id", name="unique_user_review_like"),
    )
    op.create_table(
        "review_images",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("review_id", sa.Integer(), nullable=False),
        sa.Column("filepath", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("place")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "place",
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "theme",
            postgresql.ENUM("해변", "자연", "카페", "전시", "액티비티", name="themeenum"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "address",
            postgresql.ENUM(
                "제주시",
                "서귀포시",
                "한경면",
                "한림읍",
                "애월읍",
                "조천읍",
                "구좌읍",
                "대정읍",
                "안덕면",
                "남원읍",
                "표선면",
                "성산읍",
                name="regionenum",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("latitude", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column("longitude", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="place_pkey"),
        sa.UniqueConstraint("name", name="place_name_key"),
    )
    op.drop_table("review_images")
    op.drop_table("likes")
    op.drop_table("comments")
    op.drop_table("reviews")
    # ### end Alembic commands ###
