"""travelroute_travel_route

Revision ID: e09923a19945
Revises: dd010c060f7b
Create Date: 2025-01-08 23:54:45.231866

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e09923a19945"
down_revision: Union[str, None] = "dd010c060f7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reviews", sa.Column("travel_route_id", sa.Integer(), nullable=False))
    op.drop_constraint("reviews_travelroute_id_fkey", "reviews", type_="foreignkey")
    op.create_foreign_key(None, "reviews", "travelroute", ["travel_route_id"], ["id"])
    op.drop_column("reviews", "travelroute_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reviews", sa.Column("travelroute_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint("reviews_travel_route_id_fkey", "reviews", type_="foreignkey")  # 올바른 제약 조건 이름 사용
    op.create_foreign_key(
        "reviews_travelroute_id_fkey", "reviews", "travelroute", ["travelroute_id"], ["id"]
    )  # 원래 이름으로 foreign key 복원
    op.drop_column("reviews", "travel_route_id")
    # ### end Alembic commands ###
