"""add review user relationship

Revision ID: b636ff8cbc58
Revises: 534ef42ff56a
Create Date: 2025-01-07 14:49:05.655593

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = "b636ff8cbc58"
down_revision: Union[str, None] = "534ef42ff56a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

image_source_type_enum = ENUM("upload", "link", name="imagesourcetype", create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    image_source_type_enum.create(op.get_bind(), checkfirst=True)  # type: ignore
    op.add_column(
        "review_images", sa.Column("source_type", sa.Enum("UPLOAD", "LINK", name="imagesourcetype"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("review_images", "source_type")
    image_source_type_enum.drop(op.get_bind(), checkfirst=True)  # type: ignore
    # ### end Alembic commands ###
