"""Add travel_route, travel_route_place table

Revision ID: e210e47788c1
Revises: 19377aea462a
Create Date: 2025-01-02 14:21:36.988159

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e210e47788c1"
down_revision: Union[str, None] = "19377aea462a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("travelrouteplace", "travel_route_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("travelrouteplace", "travel_route_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
