"""travel_route_lazy_select

Revision ID: 336ed60e8cee
Revises: 117b42a5d40b
Create Date: 2025-01-09 18:48:27.625452

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "336ed60e8cee"
down_revision: Union[str, None] = "117b42a5d40b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
