"""add review thumbnail update filepath

Revision ID: 8d3523112c16
Revises: e09923a19945
Create Date: 2025-01-09 13:57:46.534500

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d3523112c16"
down_revision: Union[str, None] = "e09923a19945"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("review_images", "filepath", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.add_column("reviews", sa.Column("thumbnail", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reviews", "thumbnail")
    op.alter_column("review_images", "filepath", existing_type=sa.VARCHAR(length=255), nullable=True)
    # ### end Alembic commands ###
