"""reviewimage_model_null_chage

Revision ID: dd010c060f7b
Revises: d23ff1b7ef3f
Create Date: 2025-01-08 16:19:20.478604

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dd010c060f7b"
down_revision: Union[str, None] = "d23ff1b7ef3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("review_images", "review_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("review_images", "filepath", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column(
        "review_images",
        "source_type",
        existing_type=postgresql.ENUM("upload", "link", name="imagesourcetype"),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "review_images",
        "source_type",
        existing_type=postgresql.ENUM("upload", "link", name="imagesourcetype"),
        nullable=False,
    )
    op.alter_column("review_images", "filepath", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.alter_column("review_images", "review_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
